import '../styles/globals.scss'
import store from "../app/store"
import {persistStore} from "redux-persist";
import {Provider} from "react-redux";
import {PersistGate} from "redux-persist/integration/react";
import Head from "next/head";
import {SessionProvider} from "next-auth/react"
import {ToastContainer} from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';


let persistor = persistStore(store)

function MyApp({Component, pageProps: { session, ...pageProps }}) {
	return (
		 <>
			 <Head>
				 <title>Create Next App</title>
				 <meta name="description" content="Generated by create next app"/>
				 <link rel="icon" href="/favicon.ico"/>
			 </Head>
			 <ToastContainer
				  position="top-right"
				  autoClose={5000}
				  hideProgressBar={false}
				  newestOnTop={false}
				  closeOnClick
				  rtl={false}
				  pauseOnFocusLoss
				  draggable
				  pauseOnHover
				  theme="light"
			 />
      <SessionProvider session={session}>
			 <Provider store={store}>
				 <PersistGate loading={null} persistor={persistor}>
					 <Component {...pageProps} />
				 </PersistGate>
			 </Provider>
			</SessionProvider>
		 </>
	)
}

export default MyApp
