import '../styles/globals.scss'
import store from "../store"
import {persistStore} from "redux-persist";
import {Provider} from "react-redux";
import {PersistGate} from "redux-persist/integration/react";
import Head from "next/head";

let persistor = persistStore(store)

function MyApp({Component, pageProps}) {
	return (
		 <>
			 <Head>
				 <title>Create Next App</title>
				 <meta name="description" content="Generated by create next app"/>
				 <link rel="icon" href="/favicon.ico"/>
			 </Head>

			 <Provider store={store}>
				 <PersistGate loading={null} persistor={persistor}>
					 <Component {...pageProps} />
				 </PersistGate>
			 </Provider>
		 </>
	)
}

export default MyApp
